name: wllm
channels:
  - conda-forge # smaller channel first
  - defaults
dependencies:
# versions from Google Colab
  - python==3.11.11  # Based on >=3.9 from pyproject.toml, <=3.12 for tensorflow
  - setuptools==75.1.0
  - immutabledict==4.2.0
  - numpy==1.26.0
  - optax==0.2.4 # old version tries to find jax's deprecated ShardedDeviceArray?
  - tqdm==4.67.1
  - transformers>=4.48.0 #previously ==4.43.3, but dependabot detected vulnerability
  # # - pytorch==2.4.0
  - pip
  # Optional pip dependencies (notebook, test, etc.)
  - pip:
    - flax==0.10.2 # (not optional)
    # # - jaxlib==0.4.33 # automatically included if you add [cpu] or [cuda]
    - jax[cpu]==0.4.33 #change to [cuda] for GPU support, not available in conda-forge channel
    - jaxtyping==0.2.37
    - scikit-learn #==1.6.1, moved to pip
    - torch==2.4.0 # needs python version specified?
    - tensorflow #==2.18.0
    - tensorflow-datasets>=4.9.3 # From requirements.txt
    - datasets #==3.2.0
    - huggingface_hub==0.28.1
    - ipywidgets==7.7.1
    - pandas==2.2.2
    - notebook  # Jupyter notebook package
    # - synthid-text[notebook]  # redundant?
    
    # Test dependencies
    - absl-py==1.4.0
    - mock
    - pytest