name: wllm
channels:
  - conda-forge # smaller channel first
  - defaults
dependencies:
  - setuptools>=68.0
  - python>=3.9  # Based on >=3.9 from pyproject.toml
  - immutabledict #=4.2.0
  - jaxtyping
  - numpy #=1.26.0
  - optax
  - scikit-learn
  - tqdm
  - transformers #=4.43.3
  
  # Add pip to ensure pip packages can be installed
  - pip
  
  # Optional pip dependencies (notebook, test, etc.)
  - pip:
    - torch #=2.4.0, moved to pip (not optional) 
    - flax
    - jax[cuda] # for GPU support
    - jaxlib

    - tensorflow-datasets>=4.9.3 # From requirements.txt
    - datasets
    - huggingface_hub
    - ipywidgets
    - pandas
    - tensorflow
    - notebook  # Jupyter notebook package
    - synthid-text[notebook]  # To install optional notebook-specific dependencies
    
    # Test dependencies
    - absl-py
    - mock
    - pytest