name: wllm
channels:
  - conda-forge # smaller channel first
  - defaults
dependencies:
  - setuptools>=68.0
  - python>=3.9,<3.12  # Based on >=3.9 from pyproject.toml, <3.12 for tensorflow
  - immutabledict #==4.2.0
  - jaxlib
  - jax[cuda] # for GPU support, even though it doesn't work for me on Windows
  - jaxtyping
  - numpy #==1.26.0
  - optax
  - scikit-learn
  - tqdm
  - transformers>=4.48.0 #previously ==4.43.3, but dependabot detected vulnerability
  - pytorch
  - pip
  # Optional pip dependencies (notebook, test, etc.)
  - pip:
    - flax # (not optional)
    # - torch>1.3 #=2.4.0
    - tensorflow
    - tensorflow-datasets>=4.9.3 # From requirements.txt
    - datasets
    - huggingface_hub
    - ipywidgets
    - pandas
    - notebook  # Jupyter notebook package
    - synthid-text[notebook]  # To install optional notebook-specific dependencies
    
    # Test dependencies
    - absl-py
    - mock
    - pytest